### ISSUE TITLE
Allow CORS on Response Header

### ISSUE THREAD

**Issue by ivanktanujaya** [fmidue/prolog-test-server#1]
CORS on Response Header is required for the React App to be able to access the response sent by the server. 
![image](https://user-images.githubusercontent.com/44674974/135238712-fc70a26f-db1e-4bd1-9cf4-f10d681beac3.png)

This problem is only between React App - Server Backend communication, so we won't able to replicate it with the help of Postman or curl command.
Using no-cors mode to fetch the data, however will allows the browser to get the proper response from the server, but not the React App. Using this mode will return opaque response which is basically nothing to the React App (status 0 and no data accessible by React-App)

This is the response our React-App get:
![image](https://user-images.githubusercontent.com/44674974/135239682-6d040dc4-915e-4da7-8b1c-042c6ac7371e.png)
This is what our browser gets:
![image](https://user-images.githubusercontent.com/44674974/135239998-16367d36-864a-4b79-8a67-4e6ce8253498.png)
If CORS is allowed, then on the Response Header section there will be `Access-Control-Allow-Origin` with its value.

**Comment by owestphal** [comment]
This should hopefully be fixed with 4438dba.
